# builds musescore with emscripten

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.x'
      - uses: mymindstorm/setup-emsdk@v11
      - uses: jwlawson/actions-setup-cmake@v1.11
      - uses: jurplel/install-qt-action@v2
      - name: clone musescore
        run: git clone https://github.com/musescore/musescore.git ~/mscore --depth=1
      - name: prepare for building
        run: |
          rm -rf ~/mscore/dist
          mkdir ~/mscore/dist
          cd ~/mscore/dist
      - name: configure
        run: emcmake cmake .. -DCMAKE_INSTALL_PREFIX=install_dir
      - name: build
        run: emcmaks cmake --build .
      - name: install
        run: emcmake cmake --build . --target install 
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build Musescore
